use std::fs::File;
use std::io;
use std::path::Path;

use pmtiles::{Compression, PmTilesStreamWriter, PmTilesWriter, TileType};
use tracing::info;

use omm_core::bbox::BBox;
use omm_core::error::{OmmError, OmmResult};
use omm_core::tile::TileCoord;

/// Wrapper around PMTiles stream writer for tile archive creation.
pub struct PmTilesArchive {
    writer: PmTilesStreamWriter<File>,
}

impl PmTilesArchive {
    /// Create a new PMTiles archive at the given path.
    pub fn create(
        path: &Path,
        bbox: &BBox,
        min_zoom: u8,
        max_zoom: u8,
    ) -> OmmResult<Self> {
        info!(path = %path.display(), "Creating PMTiles archive");

        let file = File::create(path)?;
        let center = bbox.center();

        let metadata = build_metadata(min_zoom, max_zoom);

        let writer = PmTilesWriter::new(TileType::Mvt)
            .tile_compression(Compression::Gzip)
            .internal_compression(Compression::Gzip)
            .min_zoom(min_zoom)
            .max_zoom(max_zoom)
            .bounds(bbox.min_lon, bbox.min_lat, bbox.max_lon, bbox.max_lat)
            .center(center.lon, center.lat)
            .center_zoom(min_zoom.saturating_add(max_zoom) / 2)
            .metadata(&metadata)
            .create(file)
            .map_err(|e| OmmError::Tile(format!("Failed to create PMTiles: {e}")))?;

        Ok(Self { writer })
    }

    /// Add a tile to the archive.
    pub fn add_tile(&mut self, coord: TileCoord, data: &[u8]) -> OmmResult<()> {
        let pm_coord = pmtiles::TileCoord::new(coord.z.0, coord.x, coord.y)
            .map_err(|e| OmmError::Tile(format!("Invalid tile coord {coord}: {e}")))?;

        self.writer
            .add_tile(pm_coord, data)
            .map_err(|e| OmmError::Tile(format!("Failed to write tile {coord}: {e}")))?;

        Ok(())
    }

    /// Finalize the archive, writing the header and directory.
    pub fn finalize(self) -> OmmResult<()> {
        self.writer
            .finalize()
            .map_err(|e| OmmError::Tile(format!("Failed to finalize PMTiles: {e}")))?;

        info!("PMTiles archive finalized");
        Ok(())
    }
}

/// Convenience function to convert OmmError for io::Error.
impl From<PmTilesArchive> for io::Result<()> {
    fn from(_: PmTilesArchive) -> Self {
        Ok(())
    }
}

/// Build TileJSON-compatible metadata for the PMTiles archive.
fn build_metadata(_min_zoom: u8, max_zoom: u8) -> String {
    let layers: Vec<serde_json::Value> = [
        ("highway", "Road network", 4),
        ("building", "Buildings", 13),
        ("water", "Water features", 0),
        ("landuse", "Land use areas", 7),
        ("natural", "Natural features", 0),
        ("railway", "Railway lines", 8),
        ("amenity", "Amenity points and areas", 13),
        ("leisure", "Leisure areas", 8),
        ("boundary", "Administrative boundaries", 2),
        ("place", "Place labels", 4),
    ]
    .iter()
    .map(|(id, desc, layer_min)| {
        serde_json::json!({
            "id": id,
            "description": desc,
            "fields": { "class": "String", "name": "String" },
            "minzoom": layer_min,
            "maxzoom": max_zoom
        })
    })
    .collect();

    serde_json::json!({
        "vector_layers": layers,
        "name": "OpenMapMarketor",
        "description": "Generated by OpenMapMarketor",
        "attribution": "OpenStreetMap contributors",
        "type": "baselayer"
    })
    .to_string()
}
